{- 
 - Solution to Project Euler problem 1
 - author: Desonte Jolivet
 - Distinct powers
 - If they are then placed in numerical order, with any repeats removed,
 - we get the following sequence of 15 distinct terms:
 - 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 -How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 -}

--Create List of tuples containing each base and power pair
powerAndBase = [(x,y)| x <- [2..100], y <- [2,100]]
